/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_parser_free: (a: number, b: number) => void;
export const parser_debug: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const parser_debugBytes: (a: number, b: number, c: number) => [number, number, number, number];
export const parser_debugLayout: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const parser_debugLayoutText: (a: number, b: number, c: number) => [number, number, number, number];
export const parser_getDeprecationWarnings: (a: number) => [number, number];
export const parser_layout: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const parser_layoutBytes: (a: number, b: number, c: number) => [number, number, number, number];
export const parser_load: (a: number, b: number, c: number) => [number, number];
export const parser_loadConfigFromJson: (a: number, b: number, c: number) => [number, number];
export const parser_new: () => number;
export const parser_parse: (a: number, b: number, c: number) => [number, number, number];
export const parser_parseBytes: (a: number, b: number, c: number) => [number, number, number];
export const parser_parseLayout: (a: number, b: number, c: number) => [number, number, number];
export const parser_parseLayoutText: (a: number, b: number, c: number) => [number, number, number];
export const parser_spec: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const parser_specBytes: (a: number, b: number, c: number) => [number, number, number, number];
export const parser_specLayout: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const parser_specLayoutText: (a: number, b: number, c: number) => [number, number, number, number];
export const parser_validateSpec: (a: number, b: number, c: number) => [number, number];
export const parser_validateSpecText: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
